/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutAppIndexRouteImport } from './routes/_appLayout/app/index'
import { Route as AppLayoutAppWorkerIndexRouteImport } from './routes/_appLayout/app/worker/index'
import { Route as AppLayoutAppCustomerIndexRouteImport } from './routes/_appLayout/app/customer/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutAppIndexRoute = AppLayoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAppWorkerIndexRoute = AppLayoutAppWorkerIndexRouteImport.update({
  id: '/app/worker/',
  path: '/app/worker/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAppCustomerIndexRoute =
  AppLayoutAppCustomerIndexRouteImport.update({
    id: '/app/customer/',
    path: '/app/customer/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/': typeof AppLayoutAppIndexRoute
  '/app/customer/': typeof AppLayoutAppCustomerIndexRoute
  '/app/worker/': typeof AppLayoutAppWorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutAppIndexRoute
  '/app/customer': typeof AppLayoutAppCustomerIndexRoute
  '/app/worker': typeof AppLayoutAppWorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_appLayout/app/': typeof AppLayoutAppIndexRoute
  '/_appLayout/app/customer/': typeof AppLayoutAppCustomerIndexRoute
  '/_appLayout/app/worker/': typeof AppLayoutAppWorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/' | '/app/customer/' | '/app/worker/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/customer' | '/app/worker'
  id:
    | '__root__'
    | '/'
    | '/_appLayout'
    | '/_appLayout/app/'
    | '/_appLayout/app/customer/'
    | '/_appLayout/app/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/app/': {
      id: '/_appLayout/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutAppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/app/worker/': {
      id: '/_appLayout/app/worker/'
      path: '/app/worker'
      fullPath: '/app/worker/'
      preLoaderRoute: typeof AppLayoutAppWorkerIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/app/customer/': {
      id: '/_appLayout/app/customer/'
      path: '/app/customer'
      fullPath: '/app/customer/'
      preLoaderRoute: typeof AppLayoutAppCustomerIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutAppIndexRoute: typeof AppLayoutAppIndexRoute
  AppLayoutAppCustomerIndexRoute: typeof AppLayoutAppCustomerIndexRoute
  AppLayoutAppWorkerIndexRoute: typeof AppLayoutAppWorkerIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutAppIndexRoute: AppLayoutAppIndexRoute,
  AppLayoutAppCustomerIndexRoute: AppLayoutAppCustomerIndexRoute,
  AppLayoutAppWorkerIndexRoute: AppLayoutAppWorkerIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
